[libraries]
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version = "5.13.4" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher", version = "1.13.4" }
jakarta-validation-api = { group = "jakarta.validation", name = "jakarta.validation-api", version = "3.1.1" }
